// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddTime(arg1:string,arg2:number):Promise<main.AddTimeResult>;

export function Ping():Promise<boolean>;

export function Settings():Promise<main.AgentSettings>;

export function Synchronization():Promise<main.SyncState>;

export function WindowsUser():Promise<string>;
