// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTime(arg1, arg2) {
  return window['go']['main']['App']['AddTime'](arg1, arg2);
}

export function Ping() {
  return window['go']['main']['App']['Ping']();
}

export function Settings() {
  return window['go']['main']['App']['Settings']();
}

export function Synchronization() {
  return window['go']['main']['App']['Synchronization']();
}

export function WindowsUser() {
  return window['go']['main']['App']['WindowsUser']();
}
